-- How many customers are there in the database?
SELECT COUNT(*) FROM customers;

-- What is the total revenue generated by product type?
SELECT products.product_type, SUM(sales.total_price) as total_revenue
FROM sales
JOIN products ON sales.product_id = products.product_ID
GROUP BY products.product_type;

--How many products were sold in a particular time period?
SELECT SUM(quantity) as total_quantity
FROM sales
JOIN orders ON sales.order_id = orders.order_id
WHERE orders.order_date BETWEEN '2021-01-01' AND '2021-04-30';

--What is the average price per unit for a specific product type?
SELECT product_type, AVG(price) as avg_price_per_unit
FROM products
WHERE product_type = 'Shirt'
GROUP BY product_type;

SELECT product_type, AVG(price) as avg_price_per_unit
FROM products
WHERE product_type = 'Jacket'
GROUP BY product_type;

SELECT product_type, AVG(price) as avg_price_per_unit
FROM products
WHERE product_type = 'Trousers'
GROUP BY product_type;

--How many orders have been made by each customer?
SELECT customers.customer_name, COUNT(orders.order_id) as num_orders
FROM customers
LEFT JOIN orders ON customers.customer_id = orders.customer_id
GROUP BY customers.customer_name;

--What is the total revenue generated by each state
SELECT customers.state, SUM(sales.total_price) as total_revenue
FROM customers
JOIN orders ON customers.customer_id = orders.customer_id
JOIN sales ON orders.order_id = sales.order_id
GROUP BY customers.state;

--What is the total revenue generated by each state
SELECT customers.city, SUM(sales.total_price) as total_revenue
FROM customers
JOIN orders ON customers.customer_id = orders.customer_id
JOIN sales ON orders.order_id = sales.order_id
GROUP BY customers.city;

--